#!/usr/bin/env bash
#Requires chwb2 from wmutils/opt

#---CONFIG---#
outerb=0x45403d
focusedb=0x807974
normalb=0x5a524c

bwidth=16
iwidth=$(( $bwidth/2 ))
owidth=$(( $bwidth/2 + $bwidth%2))
#------------#

bspc config border_width $bwidth


draw() { chwb2 -I $inner -O $outerb -i $iwidth -o $owidth $* ; }
bspc subscribe node_geometry node_focus |
	while read -r _; do
		inner=$focusedb draw "$(bspc query -N -n .local.focused.\!fullscreen)"
		inner=$normalb draw "$(bspc query -N -n .\!focused.\!fullscreen)"
	done

